server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name 146.59.93.168 vps-a3ea02a0.vps.ovh.net linktalk.pl www.linktalk.pl _;
    root /var/www/linktalk;
    index index.html;

    location = /config.js {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /downloads/ {
        try_files $uri =404;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml application/manifest+json;
}
