"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { Brand } from "@/components/Brand";
import { BellRing, CreditCard, Goal, Link2, LogOut, Settings2, Volume2 } from "lucide-react";

type Profile={id:string;username:string;display_name:string;bio:string;min_amount_grosz:number;voice_enabled:boolean;voice_min_amount_grosz:number};
type Donation={id:string;payer_name:string;amount_grosz:number;message:string;status:string;created_at:string};
export default function Dashboard(){
 const [profile,setProfile]=useState<Profile|null>(null); const [donations,setDonations]=useState<Donation[]>([]); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession(); if(!session){window.location.href="/auth?mode=login";return;} const {data:p}=await supabase.from("stream_profiles").select("id,username,display_name,bio,min_amount_grosz,voice_enabled,voice_min_amount_grosz").eq("user_id",session.user.id).maybeSingle(); if(p){setProfile(p); const {data:d}=await supabase.from("stream_donations").select("id,payer_name,amount_grosz,message,status,created_at").eq("creator_profile_id",p.id).order("created_at",{ascending:false}).limit(12); setDonations(d||[]);} setLoading(false);})();},[]);
 const paid=useMemo(()=>donations.filter(d=>d.status==="paid"),[donations]); const total=paid.reduce((s,d)=>s+d.amount_grosz,0)/100;
 async function updateMin(){if(!profile)return;const {error}=await supabase.from("stream_profiles").update({min_amount_grosz:5000,voice_min_amount_grosz:5000}).eq("id",profile.id);setNotice(error?error.message:"Ustawiono 50 PLN dla wpłat i głosówek.");}
 async function testAlert(){const {error}=await supabase.functions.invoke("stream-test-alert",{body:{amount_grosz:10000,name:"Testowy widz",message:"Test alertu DS Stream Support 💜"}});setNotice(error?`Błąd testu alertu: ${error.message}`:"Wysłano testowy alert. Otwórz overlay OBS, aby go zobaczyć.");}
 async function logout(){await supabase.auth.signOut();window.location.href="/";}
 if(loading)return <main className="dashboardShell"><div className="loading">Ładowanie panelu…</div></main>;
 return <main className="dashboardShell"><aside className="dashSidebar"><Brand compact/><nav><button className="active"><CreditCard size={18}/>Dashboard</button><button><BellRing size={18}/>Alerty</button><button><Volume2 size={18}/>Głosówki</button><button><Goal size={18}/>Cele</button><button><Link2 size={18}/>Integracje</button><button><Settings2 size={18}/>Ustawienia</button></nav><button onClick={logout} className="logout"><LogOut size={17}/>Wyloguj</button></aside><section className="dashMain"><div className="dashTop"><div><span>Panel twórcy</span><h1>{profile?.display_name||"Twórca"}</h1></div>{profile?<Link className="button ghost small" href={`/c/${profile.username}`}>Otwórz stronę wpłat</Link>:null}</div>{!profile?<div className="emptyState"><h2>Profil nie został jeszcze utworzony</h2><p>Nowe konto powinno otrzymać profil automatycznie.</p></div>:<><div className="dashCards"><article><span>Próg wpłaty</span><strong>{(profile.min_amount_grosz/100).toFixed(0)} PLN</strong></article><article><span>Wpłaty w widoku</span><strong>{donations.length}</strong></article><article><span>Suma opłaconych</span><strong>{total.toFixed(2)} PLN</strong></article><article><span>Twój URL</span><strong className="smallStrong">/c/{profile.username}</strong></article></div><section className="panelSection"><div><h2>Ustawienia płatności</h2><p>Wszystkie metody mają być dostępne od 50 PLN.</p></div><button className="button primary small" onClick={updateMin}>Ustaw wszędzie 50 PLN</button>{notice?<span className="notice">{notice}</span>:null}</section><section className="panelSection column"><div><h2>Ostatnie wpłaty</h2><p>Dane są chronione przez RLS.</p></div><div className="donationTable">{donations.length?donations.map(d=><div key={d.id}><span>{d.payer_name}</span><b>{(d.amount_grosz/100).toFixed(2)} PLN</b><em>{d.status}</em><small>{d.message||"—"}</small></div>):<p>Brak zarejestrowanych wpłat. Płatność testowa Stripe działa, automatyczne księgowanie wymaga webhooka Stripe.</p>}</div></section><section className="panelSection"><div><h2>OBS alertbox</h2><p>Dodaj jako Browser Source: <code>/overlay/{profile.username}</code></p></div><div className="inlineActions"><button className="button primary small" onClick={testAlert}>Wyślij test alert</button><Link className="button ghost small" href={`/overlay/${profile.username}`}>Podgląd overlay</Link></div></section></>}</section></main>
}
